export const ERROR_CODES = {
    /*
        E0xxx: クライアントエラー
        - E00xx: 共通エラー
        - E01xx: バリデーションエラー
    */
    ERROR_CLIENT_UNKNOWN: "E0000",
    ERROR_CLIENT_DELETED_CURRENT_CHANNEL_BY_WORKSPACE_OWNER: "E0001",
    ERROR_CLIENT_DELETED_CURRENT_WORKSPACE_BY_WORKSPACE_OWNER: "E0002",
    ERROR_CLIENT_VALIDATION_USER_ID_MIN_LENGTH: "E0100",
    ERROR_CLIENT_VALIDATION_USER_ID_MAX_LENGTH: "E0101",
    ERROR_CLIENT_VALIDATION_USER_ID_ALREADY_USED: "E0102",
    ERROR_CLIENT_VALIDATION_PASSWROD_MIN_LENGTH: "E0103",
    ERROR_CLIENT_VALIDATION_PASSWORD_MAX_LENGTH: "E0104",
    ERROR_CLIENT_VALIDATION_INCORRECT_EMAIL: "E0105",
    ERROR_CLIENT_VALIDATION_INCORRECT_PASSWORD: "E1006",
    ERROR_CLIENT_VALIDATION_COMMON_TEXT_MIN_LENGTH: "E0107",
    ERROR_CLIENT_VALIDATION_COMMON_TEXT_MAX_LENGTH: "E0108",

    /*
        E1xxx: サーバエラー
        - E10xx: 共通エラー
        - E11xx: 取得系エラー
        - E12xx: 登録系エラー
    */
    ERROR_SERVER_UNKNOWN: "E1000",
    ERROR_SERVER_FAILED_CONNECT_DB: "E1001", // P1001
    ERROR_SERVER_DB_CONNECTION_TIMEOUT: "E1002", // P1002
    ERROR_SERVER_USER_UNAUTHORIZED: "E1003",
    ERROR_SERVER_VALIDATION: "E1004",

    ERROR_SERVER_FAILED_GET_RECORDS: "E1100",
    ERROR_SERVER_NOT_FOUND_RECORDS: "E1101",

    ERROR_SERVER_FAILED_REGISTER_RECORDS: "E1200",
    ERROR_SERVER_ALREADY_REGISTERED_RECORDS: "E1201",
} as const;
