export const SUCCESS_CODES = {
    /*
        E0xxx: クライアント成功
    */
    SUCCESS_CLIENT_DELETED_OTHER_CHANNEL_BY_WORKSPACE_OWNER: "S0001",
    SUCCESS_CLIENT_DELETED_OTHER_WORKSPACE_BY_WORKSPACE_OWNER: "E0002",
} as const;
