@startuml

' =====================
' Entity definitions
' =====================
entity User {
  * userId : String [PK]
  --
  * email : String [UNIQUE]
  * displayName : String
  * password : String
  * slackToken : String [UNIQUE]
  * createdAt : DateTime
  * updatedAt : DateTime
}

entity "WorkspaceUser" as WU {
  * userId : String [PK, FK]
  * workspaceId : String [PK, FK]
}

entity Workspace {
  * workspaceId : String [PK]
  --
  * ownerId : String [FK]
  * workspaceName : String
}

entity Channel {
  * channelId : Int [PK]
  --
  * workspaceId : String [FK]
  * channelName : String
}

entity Post {
  * postId : Int [PK]
  --
  * channelId : Int [FK]
  * userId : String [FK]
  content : String?
  * createdAt : DateTime
  * updatedAt : DateTime
}

entity Profile {
    * profileId : Int [PK]
    --
    * userId : String [FK][UNIQUE]
    * imageUrl : String?
}

' =====================
' Relationships (1:N, N:M, ownership)
' =====================
' User and WU (1:N)
User ||-l-|{ WU : "1以上:1"

' Workspace and WU (1:N)
Workspace ||-l-|{ WU : "1以上:1"

' User and Workspace (1:N)
User }|--|{ Workspace : "1:1以上(owns)"

' Workspace and Channel (1:N)
Workspace ||-r-|{ Channel : "1:1以上(owns)"

' Channel and Post (1:N)
Channel ||-u-o{ Post : "1:0以上(owns)"

' User and Post (1:N)
User ||-r-o{ Post : "1:0以上(posts)"

' Profile and User (1:1)
Profile ||-d-|| User : "1:1"

@enduml
