import type { Metadata } from "next";
import { ToastProvider } from "./context/ToastContext";

import "./page.module.css";

export const metadata: Metadata = {
    title: "Copy Slack",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ja">
            <body>
                <ToastProvider>{children}</ToastProvider>
            </body>
        </html>
    );
}
