import type { Metadata } from "next";
import { CurrentUserProvider } from "./context/CurrentUserContext";
import { UserWorkspacesProvider } from "./context/UserWorkspacesContext";
import { ToastProvider } from "./context/ToastContext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <CurrentUserProvider>
                    <UserWorkspacesProvider>
                        <ToastProvider>{children}</ToastProvider>
                    </UserWorkspacesProvider>
                </CurrentUserProvider>
            </body>
        </html>
    );
}
