import type { Metadata } from "next";
import { CurrentUserProvider } from "./context/CurrentUserContext";
import { CurrentWorkspaceProvider } from "./context/CurrentWorkspaceContext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <CurrentUserProvider>
                    <CurrentWorkspaceProvider>{children}</CurrentWorkspaceProvider>
                </CurrentUserProvider>
            </body>
        </html>
    );
}
