export const ERROR_CODES = {
    // クライアントエラー
    ERROR_CLIENT_UNKNOWN: "E0000",
    ERROR_VALIDATION_USER_ID_MIN_LENGTH: "E0001",
    ERROR_VALIDATION_USER_ID_MAX_LENGTH: "E0002",
    ERROR_VALIDATION_USER_ID_ALREADY_USED: "E0003",
    ERROR_VALIDATION_PASSWROD_MIN_LENGTH: "E0004",
    ERROR_VALIDATION_PASSWORD_MAX_LENGTH: "E0005",
    ERROR_VALIDATION_INCORRECT_EMAIL: "E0006",

    // サーバエラー
    ERROR_SERVER_UNKNOWN: "E1001",
    ERROR_SERVER_USER_UNAUTHORIZED: "E1002",
    ERROR_SERVER_NOT_FOUND_USER_WORKSPACE: "E0007",
    ERROR_SERVER_WORKSPACES_DOESNT_EXIST: "E1003",
    ERROR_SERVER_CHAT_HISTORY_DOESNT_EXIST: "E1004",
    ERROR_SERVER_FAILED_REGISTER_USER: "E1005",
    ERROR_SERVER_FAILED_REGISTER_WORKSPACE: "E1006",
} as const;
