export const ERROR_CODES = {
    /*
        E0xxx: クライアントエラー
        - E00xx: 共通エラー
        - E01xx: バリデーションエラー
    */
    ERROR_CLIENT_UNKNOWN: "E0000",

    ERROR_CLIENT_VALIDATION_USER_ID_MIN_LENGTH: "E0100",
    ERROR_CLIENT_VALIDATION_USER_ID_MAX_LENGTH: "E0101",
    ERROR_CLIENT_VALIDATION_USER_ID_ALREADY_USED: "E0102",
    ERROR_CLIENT_VALIDATION_PASSWROD_MIN_LENGTH: "E0103",
    ERROR_CLIENT_VALIDATION_PASSWORD_MAX_LENGTH: "E0104",
    ERROR_CLIENT_VALIDATION_INCORRECT_EMAIL: "E0105",
    ERROR_CLIENT_VALIDATION_COMMON_TEXT_MIN_LENGTH: "E0106",
    ERROR_CLIENT_VALIDATION_COMMON_TEXT_MAX_LENGTH: "E0107",

    /*
        E1xxx: サーバエラー
        - E10xx: 共通エラー
        - E11xx: 取得系エラー
        - E12xx: 登録系エラー
    */
    ERROR_SERVER_UNKNOWN: "E1000",
    ERROR_SERVER_USER_UNAUTHORIZED: "E1001",
    ERROR_SERVER_DOESNT_EXIST_USER: "E1002",
    ERROR_SERVER_DOESNT_EXIST_WORKSPACES: "E1003",
    ERROR_SERVER_DOESNT_EXIST_USER_WORKSPACE: "E1004",
    ERROR_SERVER_DOESNT_EXIST_CHAT_HISTORY: "E1005",

    ERROR_SERVER_FAILED_GET_USERS: "E1100",
    ERROR_SERVER_FAILED_GET_CHAT_HISTORY: "E1101",
    ERROR_SERVER_FAILED_GET_WORKSPACES: "E1102",
    ERROR_SERVER_FAILED_GET_CHANNELS: "E1103",

    ERROR_SERVER_FAILED_REGISTER_USER: "E1200",
    ERROR_SERVER_FAILED_REGISTER_WORKSPACE: "E1201",
    ERROR_SERVER_FAILED_REGISTER_CHAT: "E1202",
} as const;
