export const ERROR_CODES = {
    ERROR_UNKNOWN: "E0000",
    ERROR_VALIDATION_USER_ID_MIN_LENGTH: "E0001",
    ERROR_VALIDATION_USER_ID_MAX_LENGTH: "E0002",
    ERROR_VALIDATION_USER_ID_ALREADY_USED: "E0003",
    ERROR_VALIDATION_PASSWROD_MIN_LENGTH: "E0004",
    ERROR_VALIDATION_PASSWORD_MAX_LENGTH: "E0005",
    ERROR_VALIDATION_INCORRECT_EMAIL: "E0006",
} as const;
