name: CI

on:
    push:
        branches:
            - feature/**
        paths:
            - src/app/**
            - src/tests/**
    pull_request:
        branches:
            - develop
        paths:
            - src/app/**
            - src/tests/**
    workflow_dispatch:

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - name: リポジトリのチェックアウト
              uses: actions/checkout@v4

            - name: Node.js環境の構築
              uses: actions/setup-node@v6.1.0
              with:
                  cache: npm

            - name: 依存性のインストール
              run: npm install

            - name: テスト実行
              run: npm run test
